### PR TITLE
Create Children Games.md

### PR DESCRIPTION
**Pull request by jacklehamster**

### CODE REVIEW

**Comment by leobenkel** [comment]
Can you format the idea following the template ?

**Review by leobenkel — CHANGES_REQUESTED** [review]
Cool idea :p 
Can you follow the template file ?

**Comment by jacklehamster** [comment]
It is using the template file

**Comment by leobenkel** [comment]
Nope. You copied the rendered template file instead of the raw text. You're missing the header characters : `#`

**Review by leobenkel — APPROVED** [review]

**Pull request merged**
